# action.yml
name: 'Phrase pull'
description: 'Pulls mindbox i18n resources from PhraseApp'
inputs:
  gitHubToken:
    description: 'Token to create pr-s'
    required: true
  phraseAppToken:
    description: 'Token to access PhraseApp'
    required: true
  baseBranch:
    description: 'Base branch for localization pull PR-s'
    required: false
    default: 'master'
  allowCyrillicSymbolsInCSharpComments:
    description: 'Allow cyrillic symbols in CSharp comments'
    required: false
    default: false
  autoMerge:
    description: Auto merge strategy. Posible values is github or bulldozer.
    required: false
    default: bulldozer
runs:
  using: 'docker'
  image: 'docker://mindboxmoscow/phrase-integration-gha'
  args:
   - pull
  env:
    gitHubToken: ${{ inputs.gitHubToken }}
    phraseAppToken: ${{ inputs.phraseAppToken }}
    baseBranch: ${{ inputs.baseBranch }}
    autoMerge: ${{ inputs.autoMerge }}
    allowCyrillicSymbolsInCSharpComments: ${{ inputs.allowCyrillicSymbolsInCSharpComments }}
