# action.yml
name: 'Phrase push'
description: 'Pushes new localization keys to PhraseApp'
inputs:
  phraseAppToken:
    description: 'Token to access PhraseApp'
    required: true

runs:
  using: 'docker'
  image: 'docker://mindboxmoscow/phrase-integration-gha'
  args:
   - push
  env:
    phraseAppToken: ${{ inputs.phraseAppToken }}
